In [1]:
file_path = "/home/avnish/iNeuron_Private_Intelligence_Limited/project_neuron/finance-complaint/feature_store"

In [2]:
# from tfx.components.base import executor_spec
# from tfx.components.example_gen.csv_example_gen import executor
# from tfx.components.example_gen.custom_executors import parquet_executor
# from tfx.components import FileBasedExampleGen
# example_gen = FileBasedExampleGen(
#     input_base=file_path,
#     custom_executor_spec=executor_spec.ExecutorClassSpec(parquet_executor.Executor))

In [3]:
from census_consumer_complaint.orchestrator.interactive_context_runner import CensusConsumerInteractiveContext

2022-11-12 19:30:43.302307: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-12 19:30:43.306695: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-11-12 19:30:43.306737: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [4]:
cx = CensusConsumerInteractiveContext().get_interactive_context()

In [5]:
from census_consumer_complaint.pipeline.training_pipeline import CensusConsumerTrainingPipeline

In [6]:
cctp = CensusConsumerTrainingPipeline()

In [7]:
comp = cctp.get_pipeline_component()

In [8]:
comp[0]

FileBasedExampleGen(spec: <tfx.types.standard_component_specs.FileBasedExampleGenSpec object at 0x7fd421f7c4a8>, executor_spec: <tfx.dsl.components.base.executor_spec.BeamExecutorSpec object at 0x7fd421f7c2e8>, driver_class: <class 'tfx.components.example_gen.driver.FileBasedDriver'>, component_id: FileBasedExampleGen, inputs: {}, outputs: {'examples': OutputChannel(artifact_type=Examples, producer_component_id=FileBasedExampleGen, output_key=examples, additional_properties={}, additional_custom_properties={})})

In [9]:
ingestion_output =  cx.run(comp[0])

In [10]:
stats_output = cx.run(comp[1])

In [11]:
schema_output = cx.run(comp[2])

In [12]:
example_validator = cx.run(comp[3])

In [13]:
transform = cx.run(comp[4])

running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying feature_engineering.py -> build/lib
installing to /tmp/tmps_07mtru
running install
running install_lib
copying build/lib/feature_engineering.py -> /tmp/tmps_07mtru
running install_egg_info
running egg_info
creating tfx_user_code_Transform.egg-info
writing tfx_user_code_Transform.egg-info/PKG-INFO
writing dependency_links to tfx_user_code_Transform.egg-info/dependency_links.txt
writing top-level names to tfx_user_code_Transform.egg-info/top_level.txt
writing manifest file 'tfx_user_code_Transform.egg-info/SOURCES.txt'
reading manifest file 'tfx_user_code_Transform.egg-info/SOURCES.txt'
writing manifest file 'tfx_user_code_Transform.egg-info/SOURCES.txt'
Copying tfx_user_code_Transform.egg-info to /tmp/tmps_07mtru/tfx_user_code_Transform-0.0+656f0e2f01cbc4f994c85ed3e7e4627731c18d9287717f42e7aafc21b2ad8e70-py3.7.egg-info
running install_scripts
creating /tmp/tmps_07mtru/tfx_user_code_Transform-0.0

/home/avnish/iNeuron_Private_Intelligence_Limited/project_neuron/finance-complaint/venv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,


In [14]:
transform = cx.run(comp[5])

running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying trainer.py -> build/lib
installing to /tmp/tmpjxjgyxu4
running install
running install_lib
copying build/lib/trainer.py -> /tmp/tmpjxjgyxu4
running install_egg_info
running egg_info
creating tfx_user_code_Trainer.egg-info
writing tfx_user_code_Trainer.egg-info/PKG-INFO
writing dependency_links to tfx_user_code_Trainer.egg-info/dependency_links.txt
writing top-level names to tfx_user_code_Trainer.egg-info/top_level.txt
writing manifest file 'tfx_user_code_Trainer.egg-info/SOURCES.txt'
reading manifest file 'tfx_user_code_Trainer.egg-info/SOURCES.txt'
writing manifest file 'tfx_user_code_Trainer.egg-info/SOURCES.txt'
Copying tfx_user_code_Trainer.egg-info to /tmp/tmpjxjgyxu4/tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf1684680963-py3.7.egg-info
running install_scripts


/home/avnish/iNeuron_Private_Intelligence_Limited/project_neuron/finance-complaint/venv/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,


creating /tmp/tmpjxjgyxu4/tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf1684680963.dist-info/WHEEL
creating '/tmp/tmpjq67tf4w/tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf1684680963-py3-none-any.whl' and adding '/tmp/tmpjxjgyxu4' to it
adding 'trainer.py'
adding 'tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf1684680963.dist-info/METADATA'
adding 'tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf1684680963.dist-info/WHEEL'
adding 'tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf1684680963.dist-info/top_level.txt'
adding 'tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf1684680963.dist-info/RECORD'
removing /tmp/tmpjxjgyxu4
Processing ./census_consumer_complaint_data/census_consumer_complaint/artifact/_wheels/tfx_user_code_Trainer-0.0+092529593cc0f42a7fb6a9239d37f2bf930e2ab601d93f5b681cdf168468

2022-11-12 19:30:54.726572: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-12 19:30:54.727122: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-11-12 19:30:54.727170: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-11-12 19:30:54.727208: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-11-12 19:30:54.729615: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 consumer_consent_provided_xf (  [(None, 1)]         0           []                               
 InputLayer)                                                                                      
                                                                                                  
 timely_xf (InputLayer)         [(None, 1)]          0           []                               
                                                                                                  
 state_xf (InputLayer)          [(None, 1)]          0           []                               
                                                                                                  
 product_xf (InputLayer)        [(None, 1)]          0           []                           

In [15]:
len(comp)

6

In [30]:
file_path="/home/avnish/iNeuron_Private_Intelligence_Limited/project_neuron/finance-complaint/census_consumer_complaint_data/data_source/feature_store/finance_complaint_2016-12-31_2017-12-31.parquet"

In [ ]:
import pandas as pd

In [4]:
df = pd.read_parquet(file_path)

In [5]:
df.shape

(72545, 18)

In [6]:
df.dropna(axis=0,inplace=True)

In [7]:
df.consumer_disputed.value_counts()

No     883
Yes    142
Name: consumer_disputed, dtype: int64

In [8]:
import tensorflow as tf

2022-11-10 13:31:31.845689: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-11-10 13:31:31.855983: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-11-10 13:31:31.855998: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [9]:
df

product                            complaint_what_happened  \
35      Debt collection                                                      
253     Debt collection                                                      
691     Debt collection                                                      
1634    Debt collection                                                      
2192    Debt collection                                                      
...                 ...                                                ...   
241650  Debt collection  Addendum to Case # XXXX ... .This is in regard...   
241657  Debt collection                                                      
242060  Debt collection  I have a loan from Equitable Acceptance. They ...   
242665  Debt collection  I have disputed this debt numerous times and t...   
242964  Debt collection                                                      

             date_sent_to_company                                  issue  \
35      2017-01-12T12:00:00-05:00  Cont'd attempts collect debt not owed   
253     2017-02-12T12:00:00-05:00  Cont'd attempts collect debt not owed   
691     2017-04-13T12:00:00-05:00  Cont'd attempts collect debt not owed   
1634    2017-01-10T12:00:00-05:00  Cont'd attempts collect debt not owed   
2192    2017-02-14T12:00:00-05:00                  Communication tactics   
...                           ...                                    ...   
241650  2017-03-06T12:00:00-05:00        Disclosure verification of debt   
241657  2017-03-22T12:00:00-05:00        Disclosure verification of debt   
242060  2017-03-29T12:00:00-05:00                  Communication tactics   
242665  2017-02-13T12:00:00-05:00  Cont'd attempts collect debt not owed   
242964  2017-04-18T12:00:00-05:00                  Communication tactics   

                                  sub_product zip_code            tags  \
35      Other (i.e. phone, health club, etc.)    87174   Servicemember   
253     Other (i.e. phone, health club, etc.)    11249   Servicemember   
691     Other (i.e. phone, health club, etc.)    29860   Servicemember   
1634                                  Medical    32566   Servicemember   
2192    Other (i.e. phone, health club, etc.)    29303   Servicemember   
...                                       ...      ...             ...   
241650  Other (i.e. phone, health club, etc.)    04042   Servicemember   
241657                                Medical    56688   Servicemember   
242060  Other (i.e. phone, health club, etc.)    20774   Servicemember   
242665                          I do not know    84054   Servicemember   
242964                          I do not know    46032  Older American   

        complaint_id timely consumer_consent_provided  \
35           2284205    Yes                       N/A   
253          2340354    Yes      Consent not provided   
691          2434754    Yes      Consent not provided   
1634         2282267    Yes      Consent not provided   
2192         2319821    Yes                       N/A   
...              ...    ...                       ...   
241650       2372192    Yes          Consent provided   
241657       2400323    Yes      Consent not provided   
242060       2410066    Yes          Consent provided   
242665       2341555    Yes          Consent provided   
242964       2414728    Yes      Consent not provided   

                       company_response submitted_via  \
35              Closed with explanation   Postal mail   
253                              Closed           Web   
691             Closed with explanation           Web   
1634            Closed with explanation           Web   
2192            Closed with explanation         Phone   
...                                 ...           ...   
241650          Closed with explanation           Web   
241657          Closed with explanation           Web   
242060          Closed with explanation           Web   
242665  Closed with no

In [10]:
dataset= {}
for column in df.columns:
    dataset[column]=tf.constant(df[column].values)

2022-11-10 13:32:10.061590: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-10 13:32:10.061977: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-11-10 13:32:10.062026: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-11-10 13:32:10.062056: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-11-10 13:32:10.069340: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [12]:
dataset['product']

<tf.Tensor: shape=(1025,), dtype=string, numpy=
array([b'Debt collection', b'Debt collection', b'Debt collection', ...,
       b'Debt collection', b'Debt collection', b'Debt collection'],
      dtype=object)>

In [13]:
from census_consumer_complaint.config.schema import CensusDatasetSchema

In [23]:
schema= CensusDatasetSchema()

In [24]:
dataset[schema.company]

<tf.Tensor: shape=(1025,), dtype=string, numpy=
array([b'NAVY FEDERAL CREDIT UNION', b'ERC',
       b'Monterey Financial Services LLC', ...,
       b'Equitable Acceptance Corp', b'Trident Asset Management, L.L.C.',
       b'Navient Solutions, LLC.'], dtype=object)>

In [25]:
schema.one_hot_features

['consumer_consent_provided', 'timely', 'state']

In [26]:
import tensorflow_data_validation as tfdv

In [27]:
dataset_schema = tfdv.load_schema_text("/home/avnish/iNeuron_Private_Intelligence_Limited/project_neuron/finance-complaint/census_consumer_complaint_data/census_consumer_complaint/artifact/SchemaGen/schema/134/schema.pbtxt")

In [28]:
tfdv.display_schema(dataset_schema)

Type  Presence Valency  \
Feature name                                            
'__index_level_0__'             INT  required           
'company'                     BYTES  required           
'company_public_response'    STRING  optional  single   
'company_response'           STRING  required           
'complaint_id'                  INT  required           
'complaint_what_happened'     BYTES  required           
'consumer_consent_provided'  STRING  optional  single   
'consumer_disputed'          STRING  required           
'date_received'               BYTES  required           
'date_sent_to_company'        BYTES  required           
'issue'                      STRING  required           
'product'                    STRING  required           
'state'                      STRING  optional  single   
'sub_issue'                  STRING  optional  single   
'sub_product'                STRING  optional  single   
'submitted_via'              STRING  required           
'tags'                       STRING  optional  single   
'timely'                     STRING  required           
'zip_code'                    BYTES  optional  single   

                                                  Domain  
Feature name                                              
'__index_level_0__'                                    -  
'company'                                              -  
'company_public_response'      'company_public_response'  
'company_response'                    'company_response'  
'complaint_id'                                         -  
'complaint_what_happened'                              -  
'consumer_consent_provided'  'consumer_consent_provided'  
'consumer_disputed'                  'consumer_disputed'  
'date_received'                                        -  
'date_sent_to_company'                                 -  
'issue'                                          'issue'  
'product'                                      'product'  
'state'                                          'state'  
'sub_issue'                                  'sub_issue'  
'sub_product'                              'sub_product'  
'submitted_via'                          'submitted_via'  
'tags'                                            'tags'  
'timely'                                        'timely'  
'zip_code'                                             -

Values
Domain                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
'company_public_response'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

In [30]:
schema.one_hot_features

['consumer_consent_provided', 'timely', 'state']

In [54]:
consumer_consent_vocab = tfdv.get_domain(schema=dataset_schema,feature_path=schema.consumer_consent_provided).value

In [56]:
consumer_consent_vocab

['Consent not provided', 'Consent provided', 'Consent withdrawn', 'N/A', 'Other']

In [60]:
indices = tf.range(len(consumer_consent_vocab),dtype=tf.int64)

In [61]:
indices

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [62]:
table_init = tf.lookup.KeyValueTensorInitializer(consumer_consent_vocab,indices)

In [64]:
num_oov_bucket=2
table= tf.lookup.StaticVocabularyTable(table_init,num_oov_buckets=num_oov_bucket)

In [67]:
ccp_indices = table.lookup(dataset[schema.consumer_consent_provided])

In [68]:
tf.one_hot(ccp_indices,depth=len(consumer_consent_vocab)+num_oov_bucket)

<tf.Tensor: shape=(1025, 7), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [74]:
import tensorflow_transform as tft

'issue'

In [76]:
tft.compute_and_apply_vocabulary(dataset[schema.tokenizer_feature])

RuntimeError: tf.placeholder() is not compatible with eager execution.

In [79]:
tf.timestamp

<function tensorflow.python.ops.gen_logging_ops.timestamp(name=None)>

In [16]:
import pandas as pd
df =pd.DataFrame(['0','1'])

In [17]:
df.dtypes

0    object
dtype: object

In [18]:
df

0
0  0
1  1

In [22]:
df[0].astype('int')

0    0
1    1
Name: 0, dtype: int64

In [21]:
df.dtypes

0    object
dtype: object